@startuml
title Activity Diagram - Mượn sách thư viện có Object Node

|Độc giả|
start
:Yêu cầu mượn sách;

|Thủ thư|
:Yêu cầu cung cấp TT độc giả;

|Độc giả|
:Cung cấp TT độc giả;

|Thủ thư|
:Tiếp nhận TT độc giả;

|Hệ thống|
:Kiểm tra thông tin độc giả;

if (Hợp lệ?) then (Có)

  |Thủ thư|
  :Yêu cầu cung cấp TT sách mượn;

  |Độc giả|
  :Cung cấp TT sách mượn;

  |Thủ thư|
  :Chọn sách;

  |Hệ thống|
  :Kiểm tra sách mượn;

  if (Còn sách?) then (Có)

    :Kiểm tra số lượng mượn;

    if (Vượt 3 cuốn?) then (Có)
      :Hủy cuốn vừa chọn;

      |Thủ thư|
      :Thông báo không được mượn thêm;

      |Độc giả|
      :Nhận thông báo;
      stop

    else (Không)

      |Hệ thống|
      :Lập phiếu mượn;

      |Phiếu mượn|
      :PM;

      |Hệ thống|
      fork
        :Lưu PM;
      fork again
        :Lưu CTPM;
      fork again
        :Cập nhật sách mượn;
      end fork

      :In PM;

      |Thủ thư|
      :Giao sách;

      |Độc giả|
      :Nhận sách và PM;

      stop
    endif

  else (Không)

    |Thủ thư|
    :Thông báo hết sách;

    |Độc giả|
    :Nhận thông báo hết sách;
    stop

  endif

else (Không)

  |Thủ thư|
  :Thông báo không đủ điều kiện mượn;

  |Độc giả|
  :Nhận thông báo không được mượn;
  stop

endif

@enduml